package it.fff.clientserver.common.enums;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;

@XmlEnum
public enum PlaceTypeEnum {
	STREET_ADDRESS,
	ROUTE,
	INTERSECTION,
	POLITICAL,
	COUNTRY,
	ADMINISTRATIVE_AREA_LEVEL_1,
	ADMINISTRATIVE_AREA_LEVEL_2,
	ADMINISTRATIVE_AREA_LEVEL_3,
	ADMINISTRATIVE_AREA_LEVEL_4,
	ADMINISTRATIVE_AREA_LEVEL_5,
	COLLOQUIAL_AREA,
	LOCALITY,
	SUBLOCALITY,
	SUBLOCALITY_LEVEL_1,
	SUBLOCALITY_LEVEL_2,
	SUBLOCALITY_LEVEL_3,
	SUBLOCALITY_LEVEL_4,
	SUBLOCALITY_LEVEL_5,
	NEIGHBORHOOD,
	PREMISE, 
	SUBPREMISE,
	POSTAL_CODE,
	NATURAL_FEATURE,
	AIRPORT,
	PARK,
	POINT_OF_INTEREST,
	ESTABLISHMENT,
	BUS_STATION,
	TRAIN_STATION,
	SUBWAY_STATION,
	TRANSIT_STATION,
	CHURCH,
	FINANCE,
	POST_OFFICE,
	PLACE_OF_WORSHIP,
	UNKNOW; 
	
	private int id;

	@XmlElement public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
}
